name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "ðŸ‘‹ Be nice"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
      - run: npm install -g bats
      - run: bats -v
